### PR TITLE
fix: Copy Icon is not restoring back from right tick ,when Copied

### LINKED ISSUE #3177: Copy Icon is not restoring back from right tick ,when Copied.
Here is the video preview of the docs issue.

https://github.com/user-attachments/assets/7ac5e80f-0373-48b3-ba08-3f75c4021c68

[Unexpected]
When copied, it is not restoring back to Copy Icon that It should be.
[Expected]
Button is working correctly for copying.

### PR DESCRIPTION
**Pull request by aliahmadCode**
Fixes #3177 

## PR Type
Bug

## What is the current behavior?
Currently, It is copying and then not restoring back to copy icon after some timeout

Issue Number: #3177 

## What is the new behavior?
Now, I have added the setTimeout to 2s to toggle back to copy icon.

### CODE REVIEW

File: src/app/shared/components/copy-button/copy-button.component.ts [hunk 1]
```diff
@@ -9,12 +14,20 @@ export class CopyButtonComponent {
   public elRef = inject<ElementRef<HTMLElement>>(ElementRef<HTMLElement>);
   public copied = false;
```
Comment (kamilmysliwiec) [inline src/app/shared/components/copy-button/copy-button.component.ts:16]:
```suggestion
```

File: src/app/shared/components/copy-button/copy-button.component.ts [hunk 2]
```diff
@@ -9,12 +14,20 @@ export class CopyButtonComponent {
...
   onCopy() {
     const preRef = this.elRef.nativeElement.querySelector('pre:not(.hide)');
     if (!preRef) {
       return;
     }
     navigator.clipboard.writeText(preRef.firstChild.textContent);
     this.copied = true;
+    this.cdr.detectChanges();
+
+    setTimeout(() => {
```
Comment (kamilmysliwiec) [inline src/app/shared/components/copy-button/copy-button.component.ts:28]:
```suggestion
    this.revertIconTimeout = setTimeout(() => {
```

Comment (kamilmysliwiec) [reply src/app/shared/components/copy-button/copy-button.component.ts:28]: should we assign the result of the setTimeout call to a property and `clearTimeout` in the `onDestroy` lifecycle hook?

File: src/app/shared/components/copy-button/copy-button.component.ts [hunk 3]
```diff
@@ -16,5 +24,16 @@ export class CopyButtonComponent {
     }
     navigator.clipboard.writeText(preRef.firstChild.textContent);
     this.copied = true;
+    this.cdr.detectChanges();
+
+    this.revertIconTimeout = setTimeout(() => {
+      this.copied = false;
+      this.cdr.detectChanges();
```
Comment (kamilmysliwiec) [inline src/app/shared/components/copy-button/copy-button.component.ts:31]:
```suggestion
      this.cdr.detectChanges();
      this.revertIconTimeout = null;
```

File: src/app/shared/components/copy-button/copy-button.component.ts [hunk 4]
```diff
@@ -16,5 +24,16 @@ export class CopyButtonComponent {
...
+    }, 2000);
+  }
+  ngOnDestroy(): void {
```
Comment (kamilmysliwiec) [inline src/app/shared/components/copy-button/copy-button.component.ts:34]:
```suggestion
    }, 2000);
  }
  
  ngOnDestroy(): void {
```
